// Android KeyEvent keycode constants
export const ANDROID_KEYCODES = {
  KEYCODE_UNKNOWN: 0,
  KEYCODE_HOME: 3,
  KEYCODE_BACK: 4,
  KEYCODE_0: 7,
  KEYCODE_1: 8,
  KEYCODE_2: 9,
  KEYCODE_3: 10,
  KEYCODE_4: 11,
  KEYCODE_5: 12,
  KEYCODE_6: 13,
  KEYCODE_7: 14,
  KEYCODE_8: 15,
  KEYCODE_9: 16,
  KEYCODE_DPAD_UP: 19,
  KEYCODE_DPAD_DOWN: 20,
  KEYCODE_DPAD_LEFT: 21,
  KEYCODE_DPAD_RIGHT: 22,
  KEYCODE_DPAD_CENTER: 23,
  KEYCODE_VOLUME_UP: 24,
  KEYCODE_VOLUME_DOWN: 25,
  KEYCODE_POWER: 26,
  KEYCODE_A: 29,
  KEYCODE_B: 30,
  KEYCODE_C: 31,
  KEYCODE_D: 32,
  KEYCODE_E: 33,
  KEYCODE_F: 34,
  KEYCODE_G: 35,
  KEYCODE_H: 36,
  KEYCODE_I: 37,
  KEYCODE_J: 38,
  KEYCODE_K: 39,
  KEYCODE_L: 40,
  KEYCODE_M: 41,
  KEYCODE_N: 42,
  KEYCODE_O: 43,
  KEYCODE_P: 44,
  KEYCODE_Q: 45,
  KEYCODE_R: 46,
  KEYCODE_S: 47,
  KEYCODE_T: 48,
  KEYCODE_U: 49,
  KEYCODE_V: 50,
  KEYCODE_W: 51,
  KEYCODE_X: 52,
  KEYCODE_Y: 53,
  KEYCODE_Z: 54,
  KEYCODE_COMMA: 55,
  KEYCODE_PERIOD: 56,
  KEYCODE_ALT_LEFT: 57,
  KEYCODE_ALT_RIGHT: 58,
  KEYCODE_SHIFT_LEFT: 59,
  KEYCODE_SHIFT_RIGHT: 60,
  KEYCODE_TAB: 61,
  KEYCODE_SPACE: 62,
  KEYCODE_ENTER: 66,
  KEYCODE_DEL: 67, // Backspace
  KEYCODE_GRAVE: 68,
  KEYCODE_MINUS: 69,
  KEYCODE_EQUALS: 70,
  KEYCODE_LEFT_BRACKET: 71,
  KEYCODE_RIGHT_BRACKET: 72,
  KEYCODE_BACKSLASH: 73,
  KEYCODE_SEMICOLON: 74,
  KEYCODE_APOSTROPHE: 75,
  KEYCODE_SLASH: 76,
  KEYCODE_AT: 77,
  KEYCODE_MENU: 82,
  KEYCODE_PAGE_UP: 92,
  KEYCODE_PAGE_DOWN: 93,
  KEYCODE_ESCAPE: 111,
  KEYCODE_FORWARD_DEL: 112,
  KEYCODE_CTRL_LEFT: 113,
  KEYCODE_CTRL_RIGHT: 114,
  KEYCODE_MOVE_HOME: 122,
  KEYCODE_MOVE_END: 123,
  KEYCODE_INSERT: 124,
  KEYCODE_F1: 131,
  KEYCODE_F2: 132,
  KEYCODE_F3: 133,
  KEYCODE_F4: 134,
  KEYCODE_F5: 135,
  KEYCODE_F6: 136,
  KEYCODE_F7: 137,
  KEYCODE_F8: 138,
  KEYCODE_F9: 139,
  KEYCODE_F10: 140,
  KEYCODE_F11: 141,
  KEYCODE_F12: 142,
  KEYCODE_NUMPAD_0: 144,
  KEYCODE_NUMPAD_1: 145,
  KEYCODE_NUMPAD_2: 146,
  KEYCODE_NUMPAD_3: 147,
  KEYCODE_NUMPAD_4: 148,
  KEYCODE_NUMPAD_5: 149,
  KEYCODE_NUMPAD_6: 150,
  KEYCODE_NUMPAD_7: 151,
  KEYCODE_NUMPAD_8: 152,
  KEYCODE_NUMPAD_9: 153,
  KEYCODE_NUMPAD_DIVIDE: 154,
  KEYCODE_NUMPAD_MULTIPLY: 155,
  KEYCODE_NUMPAD_SUBTRACT: 156,
  KEYCODE_NUMPAD_ADD: 157,
  KEYCODE_NUMPAD_DOT: 158,
  KEYCODE_NUMPAD_ENTER: 160,
  KEYCODE_APP_SWITCH: 187,
  KEYCODE_META_LEFT: 117,
  KEYCODE_META_RIGHT: 118,
} as const;

// Android MetaState masks
export const AMETA_ALT_ON = 0x02;
export const AMETA_ALT_LEFT_ON = 0x10;
export const AMETA_ALT_RIGHT_ON = 0x20;
export const AMETA_SHIFT_ON = 0x01;
export const AMETA_SHIFT_LEFT_ON = 0x40;
export const AMETA_SHIFT_RIGHT_ON = 0x80;
export const AMETA_CTRL_ON = 0x1000;
export const AMETA_CTRL_LEFT_ON = 0x2000;
export const AMETA_CTRL_RIGHT_ON = 0x4000;
export const AMETA_META_ON = 0x10000;

const KEY_CODE_MAP: Record<string, number> = {
  KeyA: ANDROID_KEYCODES.KEYCODE_A,
  KeyB: ANDROID_KEYCODES.KEYCODE_B,
  KeyC: ANDROID_KEYCODES.KEYCODE_C,
  KeyD: ANDROID_KEYCODES.KEYCODE_D,
  KeyE: ANDROID_KEYCODES.KEYCODE_E,
  KeyF: ANDROID_KEYCODES.KEYCODE_F,
  KeyG: ANDROID_KEYCODES.KEYCODE_G,
  KeyH: ANDROID_KEYCODES.KEYCODE_H,
  KeyI: ANDROID_KEYCODES.KEYCODE_I,
  KeyJ: ANDROID_KEYCODES.KEYCODE_J,
  KeyK: ANDROID_KEYCODES.KEYCODE_K,
  KeyL: ANDROID_KEYCODES.KEYCODE_L,
  KeyM: ANDROID_KEYCODES.KEYCODE_M,
  KeyN: ANDROID_KEYCODES.KEYCODE_N,
  KeyO: ANDROID_KEYCODES.KEYCODE_O,
  KeyP: ANDROID_KEYCODES.KEYCODE_P,
  KeyQ: ANDROID_KEYCODES.KEYCODE_Q,
  KeyR: ANDROID_KEYCODES.KEYCODE_R,
  KeyS: ANDROID_KEYCODES.KEYCODE_S,
  KeyT: ANDROID_KEYCODES.KEYCODE_T,
  KeyU: ANDROID_KEYCODES.KEYCODE_U,
  KeyV: ANDROID_KEYCODES.KEYCODE_V,
  KeyW: ANDROID_KEYCODES.KEYCODE_W,
  KeyX: ANDROID_KEYCODES.KEYCODE_X,
  KeyY: ANDROID_KEYCODES.KEYCODE_Y,
  KeyZ: ANDROID_KEYCODES.KEYCODE_Z,

  Digit0: ANDROID_KEYCODES.KEYCODE_0,
  Digit1: ANDROID_KEYCODES.KEYCODE_1,
  Digit2: ANDROID_KEYCODES.KEYCODE_2,
  Digit3: ANDROID_KEYCODES.KEYCODE_3,
  Digit4: ANDROID_KEYCODES.KEYCODE_4,
  Digit5: ANDROID_KEYCODES.KEYCODE_5,
  Digit6: ANDROID_KEYCODES.KEYCODE_6,
  Digit7: ANDROID_KEYCODES.KEYCODE_7,
  Digit8: ANDROID_KEYCODES.KEYCODE_8,
  Digit9: ANDROID_KEYCODES.KEYCODE_9,

  Enter: ANDROID_KEYCODES.KEYCODE_ENTER,
  NumpadEnter: ANDROID_KEYCODES.KEYCODE_NUMPAD_ENTER,
  Backspace: ANDROID_KEYCODES.KEYCODE_DEL,
  Delete: ANDROID_KEYCODES.KEYCODE_FORWARD_DEL,
  Tab: ANDROID_KEYCODES.KEYCODE_TAB,
  Space: ANDROID_KEYCODES.KEYCODE_SPACE,
  Escape: ANDROID_KEYCODES.KEYCODE_ESCAPE,

  ArrowUp: ANDROID_KEYCODES.KEYCODE_DPAD_UP,
  ArrowDown: ANDROID_KEYCODES.KEYCODE_DPAD_DOWN,
  ArrowLeft: ANDROID_KEYCODES.KEYCODE_DPAD_LEFT,
  ArrowRight: ANDROID_KEYCODES.KEYCODE_DPAD_RIGHT,

  Home: ANDROID_KEYCODES.KEYCODE_MOVE_HOME,
  End: ANDROID_KEYCODES.KEYCODE_MOVE_END,
  PageUp: ANDROID_KEYCODES.KEYCODE_PAGE_UP,
  PageDown: ANDROID_KEYCODES.KEYCODE_PAGE_DOWN,

  ShiftLeft: ANDROID_KEYCODES.KEYCODE_SHIFT_LEFT,
  ShiftRight: ANDROID_KEYCODES.KEYCODE_SHIFT_RIGHT,
  ControlLeft: ANDROID_KEYCODES.KEYCODE_CTRL_LEFT,
  ControlRight: ANDROID_KEYCODES.KEYCODE_CTRL_RIGHT,
  AltLeft: ANDROID_KEYCODES.KEYCODE_ALT_LEFT,
  AltRight: ANDROID_KEYCODES.KEYCODE_ALT_RIGHT,
  MetaLeft: ANDROID_KEYCODES.KEYCODE_META_LEFT,
  MetaRight: ANDROID_KEYCODES.KEYCODE_META_RIGHT,

  Comma: ANDROID_KEYCODES.KEYCODE_COMMA,
  Period: ANDROID_KEYCODES.KEYCODE_PERIOD,
  Minus: ANDROID_KEYCODES.KEYCODE_MINUS,
  Equal: ANDROID_KEYCODES.KEYCODE_EQUALS,
  BracketLeft: ANDROID_KEYCODES.KEYCODE_LEFT_BRACKET,
  BracketRight: ANDROID_KEYCODES.KEYCODE_RIGHT_BRACKET,
  Backslash: ANDROID_KEYCODES.KEYCODE_BACKSLASH,
  Semicolon: ANDROID_KEYCODES.KEYCODE_SEMICOLON,
  Quote: ANDROID_KEYCODES.KEYCODE_APOSTROPHE,
  Slash: ANDROID_KEYCODES.KEYCODE_SLASH,
  Backquote: ANDROID_KEYCODES.KEYCODE_GRAVE,

  Insert: ANDROID_KEYCODES.KEYCODE_INSERT,
  ContextMenu: ANDROID_KEYCODES.KEYCODE_MENU,

  F1: ANDROID_KEYCODES.KEYCODE_F1,
  F2: ANDROID_KEYCODES.KEYCODE_F2,
  F3: ANDROID_KEYCODES.KEYCODE_F3,
  F4: ANDROID_KEYCODES.KEYCODE_F4,
  F5: ANDROID_KEYCODES.KEYCODE_F5,
  F6: ANDROID_KEYCODES.KEYCODE_F6,
  F7: ANDROID_KEYCODES.KEYCODE_F7,
  F8: ANDROID_KEYCODES.KEYCODE_F8,
  F9: ANDROID_KEYCODES.KEYCODE_F9,
  F10: ANDROID_KEYCODES.KEYCODE_F10,
  F11: ANDROID_KEYCODES.KEYCODE_F11,
  F12: ANDROID_KEYCODES.KEYCODE_F12,

  Numpad0: ANDROID_KEYCODES.KEYCODE_NUMPAD_0,
  Numpad1: ANDROID_KEYCODES.KEYCODE_NUMPAD_1,
  Numpad2: ANDROID_KEYCODES.KEYCODE_NUMPAD_2,
  Numpad3: ANDROID_KEYCODES.KEYCODE_NUMPAD_3,
  Numpad4: ANDROID_KEYCODES.KEYCODE_NUMPAD_4,
  Numpad5: ANDROID_KEYCODES.KEYCODE_NUMPAD_5,
  Numpad6: ANDROID_KEYCODES.KEYCODE_NUMPAD_6,
  Numpad7: ANDROID_KEYCODES.KEYCODE_NUMPAD_7,
  Numpad8: ANDROID_KEYCODES.KEYCODE_NUMPAD_8,
  Numpad9: ANDROID_KEYCODES.KEYCODE_NUMPAD_9,
  NumpadDivide: ANDROID_KEYCODES.KEYCODE_NUMPAD_DIVIDE,
  NumpadMultiply: ANDROID_KEYCODES.KEYCODE_NUMPAD_MULTIPLY,
  NumpadSubtract: ANDROID_KEYCODES.KEYCODE_NUMPAD_SUBTRACT,
  NumpadAdd: ANDROID_KEYCODES.KEYCODE_NUMPAD_ADD,
  NumpadDecimal: ANDROID_KEYCODES.KEYCODE_NUMPAD_DOT,
};

/**
 * Maps browser KeyboardEvent.code to Android KeyEvent.KEYCODE_*.
 */
export function mapBrowserCodeToAndroidKeycode(code: string): number | null {
  return KEY_CODE_MAP[code] ?? null;
}

/**
 * Maps browser KeyboardEvent modifier flags to Android metaState bitmask.
 */
export function mapMetaState(modifiers: {
  ctrlKey?: boolean;
  shiftKey?: boolean;
  altKey?: boolean;
  metaKey?: boolean;
}): number {
  let meta = 0;
  if (modifiers.shiftKey) meta |= AMETA_SHIFT_ON;
  if (modifiers.ctrlKey) meta |= AMETA_CTRL_ON;
  if (modifiers.altKey) meta |= AMETA_ALT_ON;
  if (modifiers.metaKey) meta |= AMETA_META_ON;
  return meta;
}
